repos:
  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes
  - repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.3
    hooks:
      - id: check-merge-conflict
      - id: detect-private-key
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.0.9
    hooks:
      - id: shellcheck
  - repo: git://github.com/antonbabenko/pre-commit-terraform
    rev: v1.24.0
    hooks:
      - id: terraform_validate
      - id: terraform_fmt
      - id: terraform_docs
        args:
           ['--args=--sort-inputs-by-required','--args=--with-aggregate-type-defaults']

