repos:
  - repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: detect-aws-credentials
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.12
    hooks:
      - id: shellcheck
  - repo: git://github.com/antonbabenko/pre-commit-terraform
    rev: v1.50.0
    hooks:
      - id: terraform_validate
      - id: terraform_fmt
      - id: terraform_tfsec
      - id: terraform_tflint
      - id: terraform_docs
        args:
          - '--args=--sort-by-required'
  - repo: git@github.com:thlorenz/doctoc
    rev: v2.0.0
    hooks:
      - id: doctoc
        language: system
